const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const {fullApp}=require('./full-app-fixture.cjs');
test('offerte en orderbevestiging krijgen professionele PDF en Outlook-concept zonder vast From-adres',async t=>{
 const f=await fullApp(t),w=f.w,d=w.document;
 vm.runInContext("state.customers.push({id:'doc-customer',name:'Design Studio',contact:'Helen',email:'helen@example.test',street:'Main Street 1',zip:'1000 AA',city:'London',country:'United Kingdom'});state.quotes.push({id:'doc-quote',quoteNo:'Q-2026-1',orderNo:'Q-2026-1',lineNo:1,customerId:'doc-customer',name:'Alabaster pendant',qty:10,saleUnit:125,estimatedReadyDate:'2026-11-20',created:'2026-10-07',validUntil:'2026-11-07',status:'concept',paymentTerms:'50% advance',packagingTerms:'Transport excluded'});state.orders.push({id:'doc-order',orderNo:'ORD-2026-1',customerId:'doc-customer',customerName:'Design Studio',product:'Alabaster pendant',qty:10,saleUnit:125,totalSale:1250,communicatedDeadline:'2026-11-20',created:'2026-10-07',active:true,status:'confirmed'})",f.ctx);w.RALAB_PERFORMANCE.invalidate();
 w.RALAB_DOCS.openQuote('Q-2026-1');await f.wait(700);assert.ok(d.querySelector('[data-document-outlook="quote"]'));assert.ok(d.querySelector('[data-document-pdf="quote"]'));
 const qpdf=await w.RALAB_DOCUMENT_OUTLOOK.quotePdfBytes('Q-2026-1'),qdoc=await w.RALAB_DOCUMENT_OUTLOOK.create('quote','Q-2026-1'),qeml=w.RALAB_DOCUMENT_OUTLOOK.emlBytes(qdoc,'helen@example.test'),qsubject=Buffer.from(qeml.match(/Subject: =\?UTF-8\?B\?([^?]+)\?=/)[1],'base64').toString();assert.match(Buffer.from(qpdf).toString(),/^%PDF-1.4/);assert.match(Buffer.from(qpdf).toString(),/QUOTATION/);assert.match(qeml,/X-Unsent: 1\r\nTo: helen@example.test/);assert.match(qsubject,/Q-2026-1 - Alabaster pendant - rAlabaster/);assert.doesNotMatch(qeml,/\r\nFrom:/);assert.match(qeml,/Content-Disposition: attachment; filename="Quotation-Q-2026-1.pdf"/);
 const opdf=await w.RALAB_DOCUMENT_OUTLOOK.orderPdfBytes('doc-order'),odoc=await w.RALAB_DOCUMENT_OUTLOOK.create('order','doc-order'),oeml=w.RALAB_DOCUMENT_OUTLOOK.emlBytes(odoc,'helen@example.test');assert.match(Buffer.from(opdf).toString(),/ORDER CONFIRMATION/);assert.match(oeml,/Order-Confirmation-ORD-2026-1.pdf/);assert.doesNotMatch(oeml,/\r\nFrom:/);assert.deepEqual(f.errors,[]);
});
