const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {fullApp}=require('./full-app-fixture.cjs');
test('overview closes order only after review and prepares customer PDF draft',async t=>{
 const f=await fullApp(t),w=f.w,d=w.document;w.alert=()=>{};
 vm.runInContext("state.customers.push({id:'close-customer',name:'Éclairage BV',email:'inkoop@example.test',street:'Teststraat 1',zip:'1234 AB',city:'Drunen'});state.orders.push({id:'close-order',orderNo:'CLOSE-001',customerId:'close-customer',customerName:'Éclairage BV',product:'Alabaster Ø150',qty:12,saleUnit:100,totalSale:1200,costUnit:20,costing:{materialCost:5,materialMode:'unit',ops:[{name:'Draaien',rate:30,mode:'batch',minutes:90}]},active:true,deadline:'2026-10-30'});state.tasks.push({id:'close-task',orderId:'close-order',name:'Draaien',machine:'Mori',seq:1,estimate:90,actual:0,status:'open',planSegments:[{date:'2026-10-01',employee:'Kaan',start:'08:15',minutes:90}]})",f.ctx);w.RALAB_PERFORMANCE.invalidate();w.RALAB_ERP.show('orderoverview');await f.wait(60);
 vm.runInContext("state.orders.find(o=>o.id==='close-order').deadline='2026-11-05';save()",f.ctx);assert.match(f.state().orders.find(o=>o.id==='close-order').deadlineUpdatedAt,/^\d{4}-\d{2}-\d{2}T/);
 const closeButton=d.querySelector('[data-closeout-order-button="close-order"]');assert.ok(closeButton);assert.ok(closeButton.closest('.order-overview-actions'));assert.match([...d.querySelectorAll('style')].map(x=>x.textContent).join('\n'),/@media\(max-width:700px\).*order-overview-actions/s);closeButton.click();assert.ok(d.getElementById('orderCloseoutForm'));
 assert.equal(d.getElementById('closeoutStartWeightMode').value,'batch');d.getElementById('closeoutStartWeight').value='24';d.getElementById('closeoutStartWeightMode').value='unit';d.getElementById('closeoutStartWeightMode').dispatchEvent(new w.Event('change',{bubbles:true}));assert.equal(d.getElementById('closeoutStartWeight').value,'2');assert.match(d.querySelector('[data-start-weight-help]').textContent,/2 kg × 12 producten = 24 kg totaal/);
 d.querySelector('[data-closeout-actual]').value='105';d.querySelector('[data-closeout-consumption]').value='20 kg steen';d.querySelector('[data-closeout-note]').value='Interne gegevens';d.getElementById('closeoutUnitWeight').value='1';d.getElementById('closeoutMaterialPriceKg').value='3';d.getElementById('closeoutDeliveryNote').value='Breekbaar - zorgvuldig uitpakken';
 assert.equal(w.RALAB_ORDER_CLOSEOUT.finish(d.getElementById('orderCloseoutForm')),false);assert.equal(f.state().orders.find(o=>o.id==='close-order').active,true);
 d.getElementById('closeoutChecked').checked=true;d.getElementById('orderCloseoutForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await f.wait(60);
 const o=f.state().orders.find(o=>o.id==='close-order'),task=f.state().tasks.find(t=>t.id==='close-task');assert.equal(o.status,'completed');assert.ok(o.postCalculationCheckedAt);assert.match(o.orderCompletionUpdatedAt,/^\d{4}-\d{2}-\d{2}T/);assert.equal(o.startWeightMode,'unit');assert.equal(o.startWeightUnitKg,2);assert.equal(o.startWeightKg,24);assert.equal(o.yieldPct,50);assert.equal(o.materialPricePerKg,3);assert.equal(o.actualMaterialCostTotal,72);assert.equal(task.actual,105);assert.equal(task.consumption,'20 kg steen');assert.match(task.taskProgressUpdatedAt,/^\d{4}-\d{2}-\d{2}T/);assert.equal(task.planSegments.length,0);assert.equal(d.querySelector('[data-overview-order="close-order"]'),null);assert.equal(d.getElementById('completedCustomerEmail').value,'inkoop@example.test');assert.ok(d.querySelector('[data-packing-outlook]'));
 const finance=w.RALAB_COMPLETED_ORDER_ACTIONS.financials(o,[task]);assert.equal(finance.revenue,1200);assert.equal(finance.budgetCost,240);assert.equal(finance.actualCost,259.5);assert.equal(finance.actualProfit,940.5);assert.equal(finance.totalDifference,19.5);assert.deepEqual(finance.causes.map(x=>x.label),['Materiaal','Draaien']);
 const eml=w.RALAB_ORDER_CLOSEOUT.emlBytes(o,'inkoop@example.test'),pdf=w.RALAB_ORDER_CLOSEOUT.pdfBytes(o);assert.match(eml,/X-Unsent: 1\r\nTo: inkoop@example.test/);assert.doesNotMatch(eml,/\r\nFrom:/);assert.match(eml,/Content-Disposition: attachment; filename="Pakbon-CLOSE-001.pdf"/);assert.match(Buffer.from(pdf).toString(),/^%PDF-1.4/);assert.doesNotMatch(Buffer.from(pdf).toString(),/Interne gegevens|20 kg steen|105|costUnit|yieldPct/);
 if(process.env.PLANNER_VERIFY_PDF){fs.writeFileSync('/tmp/closeout-sample.pdf',Buffer.from(pdf));fs.writeFileSync('/tmp/closeout-sample.eml',eml)}
 let downloaded;w.URL.createObjectURL=file=>{downloaded=file;return 'blob:outlook-draft'};w.URL.revokeObjectURL=()=>{};w.HTMLAnchorElement.prototype.click=function(){};
 assert.equal(w.RALAB_ORDER_CLOSEOUT.delivery(o.id,'outlook'),true);await f.wait(60);const draftOrder=f.state().orders.find(x=>x.id===o.id);assert.equal(downloaded.name,'Pakbon-CLOSE-001.eml');assert.equal(downloaded.type,'message/rfc822');assert.ok(draftOrder.packingSlipDraftAt);assert.equal(draftOrder.packingSlipRecipient,'inkoop@example.test');assert.match(d.querySelector('[data-packing-draft-status]').textContent,/Concept gemaakt/);assert.match(d.querySelector('[data-packing-status]').textContent,/Concept gemaakt/);
 d.querySelector('[data-packing-sent]').click();await f.wait(60);assert.ok(f.state().orders.find(x=>x.id===o.id).packingSlipSentAt);assert.match(d.querySelector('[data-packing-status]').textContent,/Verzonden/);w.RALAB_ERP.show('completed');await f.wait(100);assert.match(d.getElementById('view-completed').textContent,/Verzonden/);
 d.querySelector('[data-packing-failed]').click();await f.wait(60);const failedOrder=f.state().orders.find(x=>x.id===o.id);assert.equal(failedOrder.packingSlipSentAt,null);assert.ok(failedOrder.packingSlipFailureAt);assert.match(d.querySelector('[data-packing-status]').textContent,/Verzending mislukt/);w.RALAB_ERP.show('completed');await f.wait(100);assert.match(d.getElementById('view-completed').textContent,/Verzending mislukt/);
 w.RALAB_CUSTOMER_MODE.set(true);assert.equal(w.RALAB_ORDER_CLOSEOUT.open(o.id),false);assert.deepEqual(f.errors,[]);
});
